# Build check

name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: Checkout and run formatter
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true
          
      - name: Verify formatting
        run: git --no-pager diff --exit-code

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
